export const UI_COPY = {
  en: {
    newCampaign: "New campaign", campaigns: "Campaigns", archived: "Archived", settings: "Settings", openSettings: "Open Settings",
    noCampaigns: "No campaigns yet.", turn: "Turn", active: "active", dead: "dead", ended: "ended", archivedStatus: "archived", working: "Working",
    welcomeTitle: "Your stories live here", welcomeBody: "Create a campaign to begin, or choose one from the sidebar.", configureLlmProvider: "Configure LLM provider",
    providerOnboardingTitle: "Welcome to llm-dungeon", providerOnboardingBody: "Connect an LLM provider in Settings, then create your first campaign and start playing.",
    providerOnboardingRecommendation: "Recommended: Google Gemini with gemini-3.5-flash.", providerOnboardingSupported: "Available for new selection: Google Gemini, OpenRouter, xAI, OpenAI, and DeepSeek.",
    providerOnboardingEnv: "Save a key in ./.env at the repository root, then restart the app.", providerOnboardingSession: "Or use the provider's ••• menu in Settings to enter a temporary session key. It stays only in server memory until restart.",
    model: "Model", provider: "Provider", campaign: "Campaign", campaignState: "Campaign state", campaignSetup: "Campaign setup", startedWith: "Started with", exportCampaign: "Export campaign log", archiveCampaign: "Archive campaign", editCampaignName: "Edit campaign name", campaignRenamed: "Campaign name updated.", save: "Save",
    ask: "Ask", appeal: "Appeal", send: "Send", actionPlaceholder: "What do you do?", submitHint: "{shortcut} to send",
    askGenericLabel: "Ask the DM without advancing the turn", askGenericTitle: "Prefill an out-of-character question; nothing is sent yet",
    appealGenericLabel: "Appeal a state or DM mistake", appealGenericTitle: "Prefill a general appeal; nothing is sent yet",
    createAdventure: "Create your adventure", createAdventureHint: "Give the dungeon master a direction, or leave the fields blank for a classic opening.",
    premise: "Premise or scenario", characterConcept: "Character concept", language: "Language", worldStyle: "World and DM style", worldSetupHint: "Prefilled from global defaults. Changes apply only to this campaign.", modelSetupHint: "Prefilled from the global default. This model generates the opening and can be changed later.", generatePreview: "Generate preview",
    preview: "Preview", character: "Character", opening: "Opening", scenarioDetails: "Scenario details", acceptBegin: "Accept and begin", regenerate: "Regenerate", editSetup: "Edit setup",
    settingsHint: "Global defaults shape new campaigns. LLM providers control tested and available models.",
    settingsSections: "Settings sections", globalDefaults: "Global defaults", globalDefaultsHint: "Used when creating a new campaign. Existing campaigns are unchanged.", defaultLanguage: "Default language", saveGlobalDefaults: "Save global defaults",
    llmProviders: "LLM providers", llmConfiguration: "LLM configuration", otherLanguages: "Other languages",
    qualityLow: "Low", qualityMedium: "Medium", qualityHigh: "High", qualityUnrated: "Unrated", qualityAwaiting: "Awaiting judgment", speedFast: "Fast", speedAverage: "Average", speedSlow: "Slow", speedVerySlow: "Very slow", speedUnrated: "Unknown", costCheap: "Low", costModerate: "Average", costExpensive: "High", costVeryExpensive: "Very high", costUnknown: "Unknown", recommended: "Recommended", providerOptions: "Provider options",
    compatibilityLabel: "Protocol", technicalClean: "Clean", technicalRecovery: "Recoverable", technicalUnstable: "Unstable", technicalUnsupported: "Unsupported", technicalInconclusive: "Unknown", modelStatusLegend: "Model status legend", legendTechnical: "Technical", legendQuality: "Quality", legendSpeed: "Speed", legendCost: "Price", legendGood: "Good", legendTowardBad: "→", legendBad: "Bad", legendUnknown: "Unknown",
    defaultModel: "Default model", activeDefault: "Default", noDefaultModel: "No default model is available.", environmentVariable: "Environment variable", keyDetected: "Key detected", environmentKeyDetected: ".env key", sessionKeyDetected: "Session key", keyMissing: "Key missing",
    sessionApiKey: "Session API key", useSessionKey: "Use key", clearSessionKey: "Clear", sessionKeyHint: "Kept only in server memory until restart. Clear it to use .env again.", sessionKeyRequired: "Enter an API key.", sessionKeySaved: "Session key is active.", sessionKeyCleared: "Session key cleared; .env fallback restored.",
    modelAvailable: "Compatible", modelDisabled: "Compatible · disabled", modelTesting: "Testing", modelFailed: "Failed", modelStale: "Retest needed", modelUntested: "Untested", modelNotAllowedByKey: "Not allowed by the provided API key", testedLanguages: "Languages",
    testModel: "Test", retestModel: "Retest", enableModel: "Enable", disableModel: "Disable", setDefault: "Set default", noProviderModels: "No configured models.", noAvailableModels: "Enable a supported model with a configured provider key before creating a campaign.",
    chooseProvider: "Choose a provider", anotherModelId: "Another model ID", modelIdPlaceholder: "Model ID", addModel: "Add", removeModel: "Remove model", modelIdRequired: "Enter a model ID.",
    modelAdded: "Custom model added. Test it before enabling it.", modelRemoved: "Custom model removed.", modelTestPassed: "Custom model test passed and the model is now available.", modelTestPartial: "Custom model available for {passed}; failed: {failed}.", modelTestFailed: "Custom model compatibility test failed.", modelAvailabilitySaved: "Model availability updated.", defaultModelSaved: "Default model updated.", needsTest: "needs test", legacyModel: "legacy current model", modelUnavailable: "This model is not currently available. Enable it in Settings or test it if it is custom.",
    closeCampaigns: "Close campaigns", openCampaigns: "Open campaigns", campaignActions: "Campaign actions", closeState: "Close campaign state", resizeCampaigns: "Resize campaigns", resizeCampaignState: "Resize campaign state",
    transcript: "Campaign transcript", whatDo: "What do you do?", sendAction: "Send action", stateViews: "Campaign state views",
    location: "Location", storyThreads: "Story threads", description: "Description", traits: "Traits", conditions: "Conditions", inventory: "Inventory",
    features: "Features", relationships: "Relationships", knownDetails: "Known details", activeThreads: "Active", resolvedThreads: "Resolved", failedThreads: "Failed", none: "None.",
    loadingState: "Loading campaign state…", stateError: "Could not load campaign state.",
    workingHint: "The dungeon master is working on this campaign.",
    pendingHint: "A request is pending. Enter :retry to resume it or :discard to remove it without changing the world.",
    pendingRequired: "Enter :retry or :discard before sending another action.", campaignFinished: "This campaign has ended and remains available for reading.",
    discarded: "Pending request discarded without changing the campaign.",
    noProvider: "Configure and test a model in Settings before creating a campaign.", missingKey: "The selected provider has no API key in .env.",
    worldSaved: "World and language defaults saved.", modelSaved: "Campaign model updated.",
    generating: "Generating preview…", creating: "Creating campaign…", archiveConfirm: "Archive this campaign? It will become read-only and cannot be resumed.", cancelArchiving: "Cancel archiving", closeCampaignSetup: "Close campaign setup", setupUnavailable: "Setup details were not recorded for this older campaign.",
    deleteCampaignLabel: "Permanently delete {title}", deleteCampaignConfirm: "This permanently deletes “{title}” and cannot be undone.", campaignDeleted: "Campaign permanently deleted.",
    permanentDeletion: "Permanent deletion", deleteCampaign: "Delete campaign", typeCampaignTitle: "Type the campaign title to confirm", cancel: "Cancel", deleteForever: "Delete forever", cancelDeletion: "Cancel deletion",
    answerNoTurn: "DM · Answer — no turn", you: "You", check: "D100 check", dm: "Dungeon Master", appealHeading: "Appeal", openingHeading: "Campaign begins", error: "Error",
    campaignCost: "Cost", present: "present", missing: "missing", defaultSource: "built-in default", localizedSource: "language override", legacySource: "legacy profile",
  },
  ru: {
    modelNotAllowedByKey: "Недоступна для предоставленного API-ключа",
    newCampaign: "Новая кампания", campaigns: "Кампании", archived: "Архив", settings: "Настройки", openSettings: "Открыть настройки",
    noCampaigns: "Кампаний пока нет.", turn: "Ход", active: "активна", dead: "персонаж погиб", ended: "завершена", archivedStatus: "в архиве", working: "Работаю",
    welcomeTitle: "Здесь живут ваши истории", welcomeBody: "Создайте кампанию или выберите существующую в боковой панели.", configureLlmProvider: "Настроить LLM-провайдера",
    providerOnboardingTitle: "Добро пожаловать в llm-dungeon", providerOnboardingBody: "Подключите LLM-провайдера в Настройках, затем создайте первую кампанию и начните играть.",
    providerOnboardingRecommendation: "Рекомендуем: Google Gemini с моделью gemini-3.5-flash.", providerOnboardingSupported: "Для нового выбора доступны Google Gemini, OpenRouter, xAI, OpenAI и DeepSeek.",
    providerOnboardingEnv: "Сохраните ключ в ./.env в корне репозитория и перезапустите приложение.", providerOnboardingSession: "Или откройте в Настройках меню ••• нужного провайдера и введите временный ключ сессии. Он хранится только в памяти сервера до перезапуска.",
    model: "Модель", provider: "Провайдер", campaign: "Кампания", campaignState: "Состояние кампании", campaignSetup: "Настройки кампании", startedWith: "Начальные настройки", exportCampaign: "Экспорт журнала", archiveCampaign: "Архивировать кампанию", editCampaignName: "Изменить название кампании", campaignRenamed: "Название кампании обновлено.", save: "Сохранить",
    ask: "Спросить", appeal: "Апелляция", send: "Отправить", actionPlaceholder: "Что вы делаете?", submitHint: "{shortcut} — отправить",
    askGenericLabel: "Задать мастеру вопрос без нового хода", askGenericTitle: "Вставить внеигровой вопрос; ничего не отправляется",
    appealGenericLabel: "Оспорить состояние игры или ошибку мастера", appealGenericTitle: "Вставить общую апелляцию; ничего не отправляется",
    createAdventure: "Создайте приключение", createAdventureHint: "Задайте мастеру направление или оставьте поля пустыми для классического начала.",
    premise: "Завязка или сценарий", characterConcept: "Концепция персонажа", language: "Язык", worldStyle: "Мир и стиль мастера", worldSetupHint: "Заполнено из общих настроек. Изменения применяются только к этой кампании.", modelSetupHint: "Заполнено из общей модели по умолчанию. Эта модель создаст начало, позже её можно сменить.", generatePreview: "Создать предпросмотр",
    preview: "Предпросмотр", character: "Персонаж", opening: "Начало", scenarioDetails: "Подробности сценария", acceptBegin: "Принять и начать", regenerate: "Создать заново", editSetup: "Изменить ввод",
    settingsHint: "Общие настройки задают новые кампании. Провайдеры LLM управляют проверенными и доступными моделями.",
    settingsSections: "Разделы настроек", globalDefaults: "Общие настройки", globalDefaultsHint: "Используются при создании новой кампании. Существующие кампании не изменяются.", defaultLanguage: "Язык по умолчанию", saveGlobalDefaults: "Сохранить общие настройки",
    llmProviders: "Провайдеры LLM", llmConfiguration: "Настройки LLM", otherLanguages: "Другие языки",
    qualityLow: "Низкое", qualityMedium: "Среднее", qualityHigh: "Высокое", qualityUnrated: "Без оценки", qualityAwaiting: "Ожидает оценки", speedFast: "Быстрая", speedAverage: "Средняя", speedSlow: "Медленная", speedVerySlow: "Очень медленная", speedUnrated: "Неизвестно", costCheap: "Низкая", costModerate: "Средняя", costExpensive: "Высокая", costVeryExpensive: "Очень высокая", costUnknown: "Неизвестно", recommended: "Рекомендуемая", providerOptions: "Настройки провайдера",
    compatibilityLabel: "Протокол", technicalClean: "Чисто", technicalRecovery: "Восстановимо", technicalUnstable: "Нестабильно", technicalUnsupported: "Не поддерживается", technicalInconclusive: "Неизвестно", modelStatusLegend: "Обозначения статуса модели", legendTechnical: "Техника", legendQuality: "Качество", legendSpeed: "Скорость", legendCost: "Цена", legendGood: "Хорошо", legendTowardBad: "→", legendBad: "Плохо", legendUnknown: "Неизвестно",
    defaultModel: "Модель по умолчанию", activeDefault: "Основная", noDefaultModel: "Нет доступной модели по умолчанию.", environmentVariable: "Переменная окружения", keyDetected: "Ключ найден", environmentKeyDetected: "Ключ .env", sessionKeyDetected: "Ключ сессии", keyMissing: "Ключ отсутствует",
    sessionApiKey: "API-ключ сессии", useSessionKey: "Использовать", clearSessionKey: "Очистить", sessionKeyHint: "Хранится только в памяти сервера до перезапуска. Очистите, чтобы снова использовать .env.", sessionKeyRequired: "Введите API-ключ.", sessionKeySaved: "Ключ сессии активен.", sessionKeyCleared: "Ключ сессии удалён; снова используется .env.",
    modelAvailable: "Совместима", modelDisabled: "Совместима · отключена", modelTesting: "Проверка", modelFailed: "Ошибка", modelStale: "Нужна проверка", modelUntested: "Не проверена", testedLanguages: "Языки",
    testModel: "Проверить", retestModel: "Проверить снова", enableModel: "Включить", disableModel: "Отключить", setDefault: "По умолчанию", noProviderModels: "Нет настроенных моделей.", noAvailableModels: "Перед созданием кампании включите поддерживаемую модель с настроенным ключом провайдера.",
    chooseProvider: "Выберите провайдера", anotherModelId: "Другая модель", modelIdPlaceholder: "ID модели", addModel: "Добавить", removeModel: "Удалить модель", modelIdRequired: "Введите ID модели.",
    modelAdded: "Пользовательская модель добавлена. Проверьте её перед включением.", modelRemoved: "Пользовательская модель удалена.", modelTestPassed: "Пользовательская модель прошла проверку и теперь доступна.", modelTestPartial: "Пользовательская модель доступна для {passed}; ошибка: {failed}.", modelTestFailed: "Пользовательская модель не прошла проверку совместимости.", modelAvailabilitySaved: "Доступность модели обновлена.", defaultModelSaved: "Модель по умолчанию обновлена.", needsTest: "нужна проверка", legacyModel: "текущая устаревшая модель", modelUnavailable: "Эта модель сейчас недоступна. Включите её в Настройках или проверьте, если это пользовательская модель.",
    closeCampaigns: "Закрыть список кампаний", openCampaigns: "Открыть список кампаний", campaignActions: "Действия кампании", closeState: "Закрыть состояние кампании", resizeCampaigns: "Изменить ширину списка кампаний", resizeCampaignState: "Изменить ширину состояния кампании",
    transcript: "Журнал кампании", whatDo: "Что вы делаете?", sendAction: "Отправить действие", stateViews: "Разделы состояния кампании",
    location: "Локация", storyThreads: "Сюжетные линии", description: "Описание", traits: "Черты", conditions: "Состояния", inventory: "Инвентарь",
    features: "Особенности", relationships: "Отношения", knownDetails: "Известные сведения", activeThreads: "Активные", resolvedThreads: "Завершённые", failedThreads: "Проваленные", none: "Нет.",
    loadingState: "Загружаю состояние кампании…", stateError: "Не удалось загрузить состояние кампании.",
    workingHint: "Мастер обрабатывает запрос этой кампании.",
    pendingHint: "Есть незавершённый запрос. Введите :retry для продолжения или :discard для удаления без изменения мира.",
    pendingRequired: "Введите :retry или :discard перед новым действием.", campaignFinished: "Кампания завершена и доступна только для чтения.",
    discarded: "Незавершённый запрос удалён без изменения кампании.",
    noProvider: "Настройте и проверьте модель перед созданием кампании.", missingKey: "Для выбранного провайдера нет API-ключа в .env.",
    worldSaved: "Настройки мира и языка сохранены.", modelSaved: "Модель кампании обновлена.",
    generating: "Создаю предпросмотр…", creating: "Создаю кампанию…", archiveConfirm: "Архивировать эту кампанию? Она станет доступна только для чтения, и продолжить её будет нельзя.", cancelArchiving: "Отменить архивацию", closeCampaignSetup: "Закрыть настройки кампании", setupUnavailable: "Начальные настройки этой старой кампании не были сохранены.",
    deleteCampaignLabel: "Удалить навсегда: {title}", deleteCampaignConfirm: "Кампания «{title}» будет удалена навсегда. Это действие нельзя отменить.", campaignDeleted: "Кампания удалена навсегда.",
    permanentDeletion: "Удаление навсегда", deleteCampaign: "Удалить кампанию", typeCampaignTitle: "Введите название кампании для подтверждения", cancel: "Отмена", deleteForever: "Удалить навсегда", cancelDeletion: "Отменить удаление",
    answerNoTurn: "Мастер · Ответ — без хода", you: "Вы", check: "Проверка d100", dm: "Мастер", appealHeading: "Апелляция", openingHeading: "Начало кампании", error: "Ошибка",
    campaignCost: "Стоимость", present: "есть", missing: "нет", defaultSource: "встроенный профиль", localizedSource: "языковой профиль", legacySource: "устаревший профиль",
  },
};

export function localeCopy(language, key) {
  const locale = UI_COPY[language] ? language : "en";
  return UI_COPY[locale][key] ?? UI_COPY.en[key] ?? key;
}
